-- Script generated by Redgate Compare v1.19.6.13227
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.widget_invoices_invoice_id_seq...';END$$;
ALTER SEQUENCE public.widget_invoices_invoice_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.widget_invoices...';END$$;
DROP TABLE public.widget_invoices;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.widget_invoices_invoice_id_seq...';END$$;
DROP SEQUENCE public.widget_invoices_invoice_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.create_invoice(text, numeric, date)...';END$$;
DROP PROCEDURE public.create_invoice(text, numeric, date);

SET check_function_bodies = true;
