-- Script generated by Redgate Compare v1.19.6.13227
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.widget_invoices...';END$$;
DROP TABLE public.widget_invoices;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.create_invoice(text, numeric, date)...';END$$;
DROP PROCEDURE public.create_invoice(text, numeric, date);

SET check_function_bodies = true;
